CC = g++
CFLAGS  = -Wall -O2 -funroll-loops -pedantic -std=c++0x -march=native -mtune=native

all:    3scenarios

3scenarios:	3scenarios.cc
	$(CC) $(CFLAGS) 3scenarios.cc -o3scenarios /home/georg/prg/g4m/increment/misc.o /home/georg/prg/g4m/increment/increment.o
