all:	2calc 3aggregate

2calc:	2calc.cc
	g++ 2calc.cc -o2calc -std=c++11 -O3 -Wall -march=native -funroll-loops -mtune=native

3aggregate:	3aggregate.cc
	g++ 3aggregate.cc -o3aggregate -std=c++11 -O3 -Wall -march=native -funroll-loops -mtune=native

