./1restruct.pl ./orig/tas_gfdl-esm2m_rcp2p6_monmed_2.csv ./orig/pr_gfdl-esm2m_rcp2p6_monmed_abs_2.csv >/tmp/dat_gfdl-esm2m_rcp2p6.txt
./1restruct.pl ./orig/tas_gfdl-esm2m_rcp8p5_monmed_2.csv ./orig/pr_gfdl-esm2m_rcp8p5_monmed_abs_2.csv >/tmp/dat_gfdl-esm2m_rcp8p5.txt
./1restruct.pl ./orig/tas_hadgem2-es_rcp2p6_monmed_2.csv ./orig/pr_hadgem2-es_rcp2p6_monmed_abs_2.csv >/tmp/dat_hadgem2-es_rcp2p6.txt
./1restruct.pl ./orig/tas_hadgem2-es_rcp4p5_monmed_2.csv ./orig/pr_hadgem2-es_rcp4p5_monmed_abs_2.csv >/tmp/dat_hadgem2-es_rcp4p5.txt
./1restruct.pl ./orig/tas_hadgem2-es_rcp6p0_monmed_2.csv ./orig/pr_hadgem2-es_rcp6p0_monmed_abs_2.csv >/tmp/dat_hadgem2-es_rcp6p0.txt
./1restruct.pl ./orig/tas_hadgem2-es_rcp8p5_monmed_2.csv ./orig/pr_hadgem2-es_rcp8p5_monmed_abs_2.csv >/tmp/dat_hadgem2-es_rcp8p5.txt
./1restruct.pl ./orig/tas_ipsl-cm5a-lr_rcp2p6_monmed_2.csv ./orig/pr_ipsl-cm5a-lr_rcp2p6_monmed_abs_2.csv >/tmp/dat_ipsl-cm5a-lr_rcp2p6.txt
./1restruct.pl ./orig/tas_ipsl-cm5a-lr_rcp8p5_monmed_2.csv ./orig/pr_ipsl-cm5a-lr_rcp8p5_monmed_abs_2.csv >/tmp/dat_ipsl-cm5a-lr_rcp8p5.txt
./1restruct.pl ./orig/tas_miroc-esm-chem_rcp2p6_monmed_2.csv ./orig/pr_miroc-esm-chem_rcp2p6_monmed_abs_2.csv >/tmp/dat_miroc-esm-chem_rcp2p6.txt
./1restruct.pl ./orig/tas_miroc-esm-chem_rcp8p5_monmed_2.csv ./orig/pr_miroc-esm-chem_rcp8p5_monmed_abs_2.csv >/tmp/dat_miroc-esm-chem_rcp8p5.txt
./1restruct.pl ./orig/tas_noresm1-m_rcp2p6_monmed_2.csv ./orig/pr_noresm1-m_rcp2p6_monmed_abs_2.csv >/tmp/dat_noresm1-m_rcp2p6.txt
./1restruct.pl ./orig/tas_noresm1-m_rcp8p5_monmed_2.csv ./orig/pr_noresm1-m_rcp8p5_monmed_abs_2.csv >/tmp/dat_noresm1-m_rcp8p5.txt
