all:	3makeCalibMap 4makeMap

3makeCalibMap:	3makeCalibMap.cc
	g++ 3makeCalibMap.cc -o3makeCalibMap -Wall -O3 -funroll-loops -march=native -std=c++0x

4makeMap:	4makeMap.cc
	g++ 4makeMap.cc -o4makeMap -Wall -O3 -funroll-loops -march=native -std=c++0x
